--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/didzo/Pictures/wallpapers/gruvbox_cofee.png"

-- Special
background="#242120"
foreground="#e2dbc9"
cursor="#e2dbc9"

-- Colors
color0="#242120"
color1="#FE8019"
color2="#C99B32"
color3="#F9BC2F"
color4="#998E75"
color5="#B3A78A"
color6="#CBBD9B"
color7="#e2dbc9"
color8="#9e998c"
color9="#FE8019"
color10="#C99B32"
color11="#F9BC2F"
color12="#998E75"
color13="#B3A78A"
color14="#CBBD9B"
color15="#e2dbc9"
