# Shell variables
# Generated by 'wal'
wallpaper='/home/didzo/Pictures/wallpapers/gruvbox_cofee.png'

# Special
background='#242120'
foreground='#e2dbc9'
cursor='#e2dbc9'

# Colors
color0='#242120'
color1='#FE8019'
color2='#C99B32'
color3='#F9BC2F'
color4='#998E75'
color5='#B3A78A'
color6='#CBBD9B'
color7='#e2dbc9'
color8='#9e998c'
color9='#FE8019'
color10='#C99B32'
color11='#F9BC2F'
color12='#998E75'
color13='#B3A78A'
color14='#CBBD9B'
color15='#e2dbc9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
